# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'app.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CaseClosed(object):
    def setupUi(self, CaseClosed):
        CaseClosed.setObjectName("CaseClosed")
        CaseClosed.resize(303, 512)
        self.centralwidget = QtWidgets.QWidget(CaseClosed)
        self.centralwidget.setObjectName("centralwidget")
        self.Button_emprunter = QtWidgets.QPushButton(self.centralwidget)
        self.Button_emprunter.setGeometry(QtCore.QRect(40, 40, 93, 28))
        self.Button_emprunter.setObjectName("Button_emprunter")
        self.Button_rendre = QtWidgets.QPushButton(self.centralwidget)
        self.Button_rendre.setGeometry(QtCore.QRect(160, 40, 93, 28))
        self.Button_rendre.setObjectName("Button_rendre")
        self.Button_mainboard = QtWidgets.QPushButton(self.centralwidget)
        self.Button_mainboard.setGeometry(QtCore.QRect(0, 0, 30, 30))
        self.Button_mainboard.setIconSize(QtCore.QSize(5, 5))
        self.Button_mainboard.setObjectName("Button_mainboard")
        CaseClosed.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(CaseClosed)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 303, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuAdmin = QtWidgets.QMenu(self.menubar)
        self.menuAdmin.setObjectName("menuAdmin")
        CaseClosed.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(CaseClosed)
        self.statusbar.setObjectName("statusbar")
        CaseClosed.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuAdmin.menuAction())

        self.retranslateUi(CaseClosed)
        QtCore.QMetaObject.connectSlotsByName(CaseClosed)

    def retranslateUi(self, CaseClosed):
        _translate = QtCore.QCoreApplication.translate
        CaseClosed.setWindowTitle(_translate("CaseClosed", "CaseClosed"))
        self.Button_emprunter.setText(_translate("CaseClosed", "Emprunter"))
        self.Button_rendre.setText(_translate("CaseClosed", "Rendre"))
        self.Button_mainboard.setText(_translate("CaseClosed", "←"))
        self.menuFile.setTitle(_translate("CaseClosed", "Accueil"))
        self.menuAdmin.setTitle(_translate("CaseClosed", "Admin"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CaseClosed = QtWidgets.QMainWindow()
    ui = Ui_CaseClosed()
    ui.setupUi(CaseClosed)
    CaseClosed.show()
    sys.exit(app.exec_())
